version: "3"
services:

  web:
    build: ./web
    image: cide/uploader
    ports:
      - 8080:8080
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./web/client:/usr/src/app/client
      - ./web/views:/usr/src/app/views
      - ./web/data:/usr/src/app/data

  mongo:
    image: mongo:3.6
    volumes:
      - ./mongo:/data/db
    restart: always
